/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAssociacoesRouteImport } from './routes/_authenticated/admin.associacoes'
import { Route as AuthenticatedAdminDiagnosticosRouteImport } from './routes/_authenticated/admin.diagnosticos'
import { Route as AuthenticatedAdminImportarRouteImport } from './routes/_authenticated/admin.importar'
import { Route as AuthenticatedAdminNovoRouteImport } from './routes/_authenticated/admin.novo'
import { Route as AuthenticatedAdminPerfilRouteImport } from './routes/_authenticated/admin.perfil'
import { Route as AuthenticatedAdminTrocarSenhaRouteImport } from './routes/_authenticated/admin.trocar-senha'
import { Route as AuthenticatedAdminIdIndexRouteImport } from './routes/_authenticated/admin.$id.index'
import { Route as AuthenticatedAdminIdEditarRouteImport } from './routes/_authenticated/admin.$id.editar'
import { Route as AuthenticatedAdminAssociacoesIndexRouteImport } from './routes/_authenticated/admin.associacoes.index'
import { Route as AuthenticatedAdminAssociacoesNovaRouteImport } from './routes/_authenticated/admin.associacoes.nova'
import { Route as AuthenticatedAdminUsuariosIndexRouteImport } from './routes/_authenticated/admin.usuarios.index'
import { Route as AuthenticatedAdminUsuariosNovoRouteImport } from './routes/_authenticated/admin.usuarios.novo'
import { Route as AuthenticatedAdminAssociacoesIdIndexRouteImport } from './routes/_authenticated/admin.associacoes.$id.index'
import { Route as AuthenticatedAdminAssociacoesIdDocumentosRouteImport } from './routes/_authenticated/admin.associacoes.$id.documentos'
import { Route as AuthenticatedAdminAssociacoesIdEditarRouteImport } from './routes/_authenticated/admin.associacoes.$id.editar'
import { Route as AuthenticatedAdminUsuariosUserIdEditarRouteImport } from './routes/_authenticated/admin.usuarios.$userId.editar'
import { Route as AuthenticatedAdminAssociacoesIdCatadoresNovoRouteImport } from './routes/_authenticated/admin.associacoes.$id.catadores.novo'
import { Route as AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRouteImport } from './routes/_authenticated/admin.associacoes.$id.diagnostico.$assessmentId'
import { Route as AuthenticatedAdminAssociacoesIdDiagnosticoNovoRouteImport } from './routes/_authenticated/admin.associacoes.$id.diagnostico.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAssociacoesRoute =
  AuthenticatedAdminAssociacoesRouteImport.update({
    id: '/associacoes',
    path: '/associacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiagnosticosRoute =
  AuthenticatedAdminDiagnosticosRouteImport.update({
    id: '/diagnosticos',
    path: '/diagnosticos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportarRoute =
  AuthenticatedAdminImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNovoRoute = AuthenticatedAdminNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPerfilRoute =
  AuthenticatedAdminPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrocarSenhaRoute =
  AuthenticatedAdminTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIdIndexRoute =
  AuthenticatedAdminIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIdEditarRoute =
  AuthenticatedAdminIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssociacoesIndexRoute =
  AuthenticatedAdminAssociacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAssociacoesRoute,
  } as any)
const AuthenticatedAdminAssociacoesNovaRoute =
  AuthenticatedAdminAssociacoesNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedAdminAssociacoesRoute,
  } as any)
const AuthenticatedAdminUsuariosIndexRoute =
  AuthenticatedAdminUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosNovoRoute =
  AuthenticatedAdminUsuariosNovoRouteImport.update({
    id: '/usuarios/novo',
    path: '/usuarios/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdIndexRoute =
  AuthenticatedAdminAssociacoesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedAdminAssociacoesRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdDocumentosRoute =
  AuthenticatedAdminAssociacoesIdDocumentosRouteImport.update({
    id: '/$id/documentos',
    path: '/$id/documentos',
    getParentRoute: () => AuthenticatedAdminAssociacoesRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdEditarRoute =
  AuthenticatedAdminAssociacoesIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedAdminAssociacoesRoute,
  } as any)
const AuthenticatedAdminUsuariosUserIdEditarRoute =
  AuthenticatedAdminUsuariosUserIdEditarRouteImport.update({
    id: '/usuarios/$userId/editar',
    path: '/usuarios/$userId/editar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdCatadoresNovoRoute =
  AuthenticatedAdminAssociacoesIdCatadoresNovoRouteImport.update({
    id: '/$id/catadores/novo',
    path: '/$id/catadores/novo',
    getParentRoute: () => AuthenticatedAdminAssociacoesRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute =
  AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRouteImport.update({
    id: '/$id/diagnostico/$assessmentId',
    path: '/$id/diagnostico/$assessmentId',
    getParentRoute: () => AuthenticatedAdminAssociacoesRoute,
  } as any)
const AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute =
  AuthenticatedAdminAssociacoesIdDiagnosticoNovoRouteImport.update({
    id: '/$id/diagnostico/novo',
    path: '/$id/diagnostico/novo',
    getParentRoute: () => AuthenticatedAdminAssociacoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/associacoes': typeof AuthenticatedAdminAssociacoesRouteWithChildren
  '/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/trocar-senha': typeof AuthenticatedAdminTrocarSenhaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/admin/$id/': typeof AuthenticatedAdminIdIndexRoute
  '/admin/associacoes/': typeof AuthenticatedAdminAssociacoesIndexRoute
  '/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/admin/associacoes/$id/documentos': typeof AuthenticatedAdminAssociacoesIdDocumentosRoute
  '/admin/associacoes/$id/editar': typeof AuthenticatedAdminAssociacoesIdEditarRoute
  '/admin/usuarios/$userId/editar': typeof AuthenticatedAdminUsuariosUserIdEditarRoute
  '/admin/associacoes/$id/': typeof AuthenticatedAdminAssociacoesIdIndexRoute
  '/admin/associacoes/$id/catadores/novo': typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRoute
  '/admin/associacoes/$id/diagnostico/$assessmentId': typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute
  '/admin/associacoes/$id/diagnostico/novo': typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/trocar-senha': typeof AuthenticatedAdminTrocarSenhaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/admin/$id': typeof AuthenticatedAdminIdIndexRoute
  '/admin/associacoes': typeof AuthenticatedAdminAssociacoesIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosIndexRoute
  '/admin/associacoes/$id/documentos': typeof AuthenticatedAdminAssociacoesIdDocumentosRoute
  '/admin/associacoes/$id/editar': typeof AuthenticatedAdminAssociacoesIdEditarRoute
  '/admin/usuarios/$userId/editar': typeof AuthenticatedAdminUsuariosUserIdEditarRoute
  '/admin/associacoes/$id': typeof AuthenticatedAdminAssociacoesIdIndexRoute
  '/admin/associacoes/$id/catadores/novo': typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRoute
  '/admin/associacoes/$id/diagnostico/$assessmentId': typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute
  '/admin/associacoes/$id/diagnostico/novo': typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/associacoes': typeof AuthenticatedAdminAssociacoesRouteWithChildren
  '/_authenticated/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/_authenticated/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/_authenticated/admin/novo': typeof AuthenticatedAdminNovoRoute
  '/_authenticated/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/_authenticated/admin/trocar-senha': typeof AuthenticatedAdminTrocarSenhaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/$id/editar': typeof AuthenticatedAdminIdEditarRoute
  '/_authenticated/admin/associacoes/nova': typeof AuthenticatedAdminAssociacoesNovaRoute
  '/_authenticated/admin/usuarios/novo': typeof AuthenticatedAdminUsuariosNovoRoute
  '/_authenticated/admin/$id/': typeof AuthenticatedAdminIdIndexRoute
  '/_authenticated/admin/associacoes/': typeof AuthenticatedAdminAssociacoesIndexRoute
  '/_authenticated/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/_authenticated/admin/associacoes/$id/documentos': typeof AuthenticatedAdminAssociacoesIdDocumentosRoute
  '/_authenticated/admin/associacoes/$id/editar': typeof AuthenticatedAdminAssociacoesIdEditarRoute
  '/_authenticated/admin/usuarios/$userId/editar': typeof AuthenticatedAdminUsuariosUserIdEditarRoute
  '/_authenticated/admin/associacoes/$id/': typeof AuthenticatedAdminAssociacoesIdIndexRoute
  '/_authenticated/admin/associacoes/$id/catadores/novo': typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRoute
  '/_authenticated/admin/associacoes/$id/diagnostico/$assessmentId': typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute
  '/_authenticated/admin/associacoes/$id/diagnostico/novo': typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/associacoes'
    | '/admin/diagnosticos'
    | '/admin/importar'
    | '/admin/novo'
    | '/admin/perfil'
    | '/admin/trocar-senha'
    | '/admin/'
    | '/admin/$id/editar'
    | '/admin/associacoes/nova'
    | '/admin/usuarios/novo'
    | '/admin/$id/'
    | '/admin/associacoes/'
    | '/admin/usuarios/'
    | '/admin/associacoes/$id/documentos'
    | '/admin/associacoes/$id/editar'
    | '/admin/usuarios/$userId/editar'
    | '/admin/associacoes/$id/'
    | '/admin/associacoes/$id/catadores/novo'
    | '/admin/associacoes/$id/diagnostico/$assessmentId'
    | '/admin/associacoes/$id/diagnostico/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/diagnosticos'
    | '/admin/importar'
    | '/admin/novo'
    | '/admin/perfil'
    | '/admin/trocar-senha'
    | '/admin'
    | '/admin/$id/editar'
    | '/admin/associacoes/nova'
    | '/admin/usuarios/novo'
    | '/admin/$id'
    | '/admin/associacoes'
    | '/admin/usuarios'
    | '/admin/associacoes/$id/documentos'
    | '/admin/associacoes/$id/editar'
    | '/admin/usuarios/$userId/editar'
    | '/admin/associacoes/$id'
    | '/admin/associacoes/$id/catadores/novo'
    | '/admin/associacoes/$id/diagnostico/$assessmentId'
    | '/admin/associacoes/$id/diagnostico/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/associacoes'
    | '/_authenticated/admin/diagnosticos'
    | '/_authenticated/admin/importar'
    | '/_authenticated/admin/novo'
    | '/_authenticated/admin/perfil'
    | '/_authenticated/admin/trocar-senha'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/$id/editar'
    | '/_authenticated/admin/associacoes/nova'
    | '/_authenticated/admin/usuarios/novo'
    | '/_authenticated/admin/$id/'
    | '/_authenticated/admin/associacoes/'
    | '/_authenticated/admin/usuarios/'
    | '/_authenticated/admin/associacoes/$id/documentos'
    | '/_authenticated/admin/associacoes/$id/editar'
    | '/_authenticated/admin/usuarios/$userId/editar'
    | '/_authenticated/admin/associacoes/$id/'
    | '/_authenticated/admin/associacoes/$id/catadores/novo'
    | '/_authenticated/admin/associacoes/$id/diagnostico/$assessmentId'
    | '/_authenticated/admin/associacoes/$id/diagnostico/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes': {
      id: '/_authenticated/admin/associacoes'
      path: '/associacoes'
      fullPath: '/admin/associacoes'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnosticos': {
      id: '/_authenticated/admin/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/admin/diagnosticos'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/importar': {
      id: '/_authenticated/admin/importar'
      path: '/importar'
      fullPath: '/admin/importar'
      preLoaderRoute: typeof AuthenticatedAdminImportarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/novo': {
      id: '/_authenticated/admin/novo'
      path: '/novo'
      fullPath: '/admin/novo'
      preLoaderRoute: typeof AuthenticatedAdminNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/perfil': {
      id: '/_authenticated/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AuthenticatedAdminPerfilRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trocar-senha': {
      id: '/_authenticated/admin/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/admin/trocar-senha'
      preLoaderRoute: typeof AuthenticatedAdminTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id/': {
      id: '/_authenticated/admin/$id/'
      path: '/$id'
      fullPath: '/admin/$id/'
      preLoaderRoute: typeof AuthenticatedAdminIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id/editar': {
      id: '/_authenticated/admin/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/$id/editar'
      preLoaderRoute: typeof AuthenticatedAdminIdEditarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes/': {
      id: '/_authenticated/admin/associacoes/'
      path: '/'
      fullPath: '/admin/associacoes/'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAssociacoesRoute
    }
    '/_authenticated/admin/associacoes/nova': {
      id: '/_authenticated/admin/associacoes/nova'
      path: '/nova'
      fullPath: '/admin/associacoes/nova'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesNovaRouteImport
      parentRoute: typeof AuthenticatedAdminAssociacoesRoute
    }
    '/_authenticated/admin/usuarios/': {
      id: '/_authenticated/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios/novo': {
      id: '/_authenticated/admin/usuarios/novo'
      path: '/usuarios/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes/$id/': {
      id: '/_authenticated/admin/associacoes/$id/'
      path: '/$id'
      fullPath: '/admin/associacoes/$id/'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAssociacoesRoute
    }
    '/_authenticated/admin/associacoes/$id/documentos': {
      id: '/_authenticated/admin/associacoes/$id/documentos'
      path: '/$id/documentos'
      fullPath: '/admin/associacoes/$id/documentos'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdDocumentosRouteImport
      parentRoute: typeof AuthenticatedAdminAssociacoesRoute
    }
    '/_authenticated/admin/associacoes/$id/editar': {
      id: '/_authenticated/admin/associacoes/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/associacoes/$id/editar'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdEditarRouteImport
      parentRoute: typeof AuthenticatedAdminAssociacoesRoute
    }
    '/_authenticated/admin/usuarios/$userId/editar': {
      id: '/_authenticated/admin/usuarios/$userId/editar'
      path: '/usuarios/$userId/editar'
      fullPath: '/admin/usuarios/$userId/editar'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosUserIdEditarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/associacoes/$id/catadores/novo': {
      id: '/_authenticated/admin/associacoes/$id/catadores/novo'
      path: '/$id/catadores/novo'
      fullPath: '/admin/associacoes/$id/catadores/novo'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRouteImport
      parentRoute: typeof AuthenticatedAdminAssociacoesRoute
    }
    '/_authenticated/admin/associacoes/$id/diagnostico/$assessmentId': {
      id: '/_authenticated/admin/associacoes/$id/diagnostico/$assessmentId'
      path: '/$id/diagnostico/$assessmentId'
      fullPath: '/admin/associacoes/$id/diagnostico/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedAdminAssociacoesRoute
    }
    '/_authenticated/admin/associacoes/$id/diagnostico/novo': {
      id: '/_authenticated/admin/associacoes/$id/diagnostico/novo'
      path: '/$id/diagnostico/novo'
      fullPath: '/admin/associacoes/$id/diagnostico/novo'
      preLoaderRoute: typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRouteImport
      parentRoute: typeof AuthenticatedAdminAssociacoesRoute
    }
  }
}

interface AuthenticatedAdminAssociacoesRouteChildren {
  AuthenticatedAdminAssociacoesNovaRoute: typeof AuthenticatedAdminAssociacoesNovaRoute
  AuthenticatedAdminAssociacoesIndexRoute: typeof AuthenticatedAdminAssociacoesIndexRoute
  AuthenticatedAdminAssociacoesIdDocumentosRoute: typeof AuthenticatedAdminAssociacoesIdDocumentosRoute
  AuthenticatedAdminAssociacoesIdEditarRoute: typeof AuthenticatedAdminAssociacoesIdEditarRoute
  AuthenticatedAdminAssociacoesIdIndexRoute: typeof AuthenticatedAdminAssociacoesIdIndexRoute
  AuthenticatedAdminAssociacoesIdCatadoresNovoRoute: typeof AuthenticatedAdminAssociacoesIdCatadoresNovoRoute
  AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute: typeof AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute
  AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute: typeof AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute
}

const AuthenticatedAdminAssociacoesRouteChildren: AuthenticatedAdminAssociacoesRouteChildren =
  {
    AuthenticatedAdminAssociacoesNovaRoute:
      AuthenticatedAdminAssociacoesNovaRoute,
    AuthenticatedAdminAssociacoesIndexRoute:
      AuthenticatedAdminAssociacoesIndexRoute,
    AuthenticatedAdminAssociacoesIdDocumentosRoute:
      AuthenticatedAdminAssociacoesIdDocumentosRoute,
    AuthenticatedAdminAssociacoesIdEditarRoute:
      AuthenticatedAdminAssociacoesIdEditarRoute,
    AuthenticatedAdminAssociacoesIdIndexRoute:
      AuthenticatedAdminAssociacoesIdIndexRoute,
    AuthenticatedAdminAssociacoesIdCatadoresNovoRoute:
      AuthenticatedAdminAssociacoesIdCatadoresNovoRoute,
    AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute:
      AuthenticatedAdminAssociacoesIdDiagnosticoAssessmentIdRoute,
    AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute:
      AuthenticatedAdminAssociacoesIdDiagnosticoNovoRoute,
  }

const AuthenticatedAdminAssociacoesRouteWithChildren =
  AuthenticatedAdminAssociacoesRoute._addFileChildren(
    AuthenticatedAdminAssociacoesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAssociacoesRoute: typeof AuthenticatedAdminAssociacoesRouteWithChildren
  AuthenticatedAdminDiagnosticosRoute: typeof AuthenticatedAdminDiagnosticosRoute
  AuthenticatedAdminImportarRoute: typeof AuthenticatedAdminImportarRoute
  AuthenticatedAdminNovoRoute: typeof AuthenticatedAdminNovoRoute
  AuthenticatedAdminPerfilRoute: typeof AuthenticatedAdminPerfilRoute
  AuthenticatedAdminTrocarSenhaRoute: typeof AuthenticatedAdminTrocarSenhaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminIdEditarRoute: typeof AuthenticatedAdminIdEditarRoute
  AuthenticatedAdminUsuariosNovoRoute: typeof AuthenticatedAdminUsuariosNovoRoute
  AuthenticatedAdminIdIndexRoute: typeof AuthenticatedAdminIdIndexRoute
  AuthenticatedAdminUsuariosIndexRoute: typeof AuthenticatedAdminUsuariosIndexRoute
  AuthenticatedAdminUsuariosUserIdEditarRoute: typeof AuthenticatedAdminUsuariosUserIdEditarRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAssociacoesRoute:
    AuthenticatedAdminAssociacoesRouteWithChildren,
  AuthenticatedAdminDiagnosticosRoute: AuthenticatedAdminDiagnosticosRoute,
  AuthenticatedAdminImportarRoute: AuthenticatedAdminImportarRoute,
  AuthenticatedAdminNovoRoute: AuthenticatedAdminNovoRoute,
  AuthenticatedAdminPerfilRoute: AuthenticatedAdminPerfilRoute,
  AuthenticatedAdminTrocarSenhaRoute: AuthenticatedAdminTrocarSenhaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminIdEditarRoute: AuthenticatedAdminIdEditarRoute,
  AuthenticatedAdminUsuariosNovoRoute: AuthenticatedAdminUsuariosNovoRoute,
  AuthenticatedAdminIdIndexRoute: AuthenticatedAdminIdIndexRoute,
  AuthenticatedAdminUsuariosIndexRoute: AuthenticatedAdminUsuariosIndexRoute,
  AuthenticatedAdminUsuariosUserIdEditarRoute:
    AuthenticatedAdminUsuariosUserIdEditarRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
